stages:
  - publish
  - staging
  - deploy
variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  SERVER_PATH: /root/notebook/userside
publish:
  image: docker:git
  stage: publish
  services:
    - docker:dind
  script:
    - cat $ENV_FILE > .env
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
  only:
    - dev
    - main
deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= ${ID_RSA}
    - apk update && apk add openssh-client
    - ssh -i ${ID_RSA} -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY &&
      cd $SERVER_PATH &&
      docker-compose down &&
      docker container rm -f $TAG_LATEST || true &&
      docker pull $TAG_LATEST &&
      docker-compose up -d"
  environment:
    name: production
    url: http://138.68.125.153
  only:
    - main
